version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project_TABEYOUKA_docker-compose-repo/
    overwrite: yes

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
